name: Trigger S3 Upload for Dev-Build

on:
  push:
    branches:
      - dev-build
  workflow_dispatch:

jobs:
  call-reusable:
    uses: UnityGames-UPS/unity-build-pipeline/.github/workflows/main.yml@main
    with:
      s3_folder: dev/OT-CR2
